import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import CustomMenuBar from '../layoutComponents/menuBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <CustomMenuBar TitleName={'ようこそ'} />
      {children}
    </>
  );
}
